### ISSUE TITLE
Simple code causes max_length warning

### ISSUE THREAD

**Issue by ssamt** [FlagOpen/FlagEmbedding#1237]
```
reranking_model = 'BAAI/bge-reranker-v2-m3'
reranker = FlagReranker(reranking_model)

if __name__ == '__main__':
    reranker.compute_score(['query', 'paragraph'])
```

> /home/november/miniconda3/envs/november/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.

This error is raised for every iteration. How can I fix this?

**Comment by hanhainebula** [comment]
Hello, @ssamt. This is caused by adding `max_length` parameter when using `tokenizer.pad()`. We just fixed this issue in [this commit](https://github.com/FlagOpen/FlagEmbedding/commit/5702c808193d19a30c0711c88a4f10a512e7524b). You can try the new code now. Looking forward to your feedback.

**Comment by zhongxifang** [comment]
@hanhainebula 

The same issue still occurs during the fine-tuning of bge-m3. I assume that the reranker part has been fixed, but the embedding part has not. 

.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
